# -*- coding: utf-8 -*-
# vim: ft=yaml
---
homeassistant:
  pkg:
    name: homeassistant
  rootgroup: root
  config: '/etc/homeassistant'
  service:
    name: homeassistant
  subcomponent:
    config: '/etc/homeassistant-subcomponent-formula.conf'
  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults
