# -*- coding: utf-8 -*-
# vim: ft=yaml
---
homeassistant:
  install_from_src: True
  pkg:
    name: python3-homeassistant
  src:
    name: homeassistant
    pkgs:
      - python3
      - python3-devel
      - python3-pip
      - libffi-devel
      - gcc
      - python3-virtualenv
      - zlib-devel
      - libjpeg-devel
      # official debian requirements pkgs tranlated to Fedora:
      # python3 python3-devel python3-pip libffi-devel openssl-devel libjpeg-devel zlib-devel autoconf openjpeg2 libtiff gcc
    groups:
      - dialout
      #- gpio
      #- i2c

  user: homeassistant
  homedir: '/srv/homeassistant'
  config: '/etc/homeassistant'
  service:
    name: homeassistant
